[general]
renice=10
desiredgov=performance
igpu_desiredgov=performance
softrealtime=auto

[custom]
; Al arrancar un juego: perfil gaming + afinidad al CCD con V-Cache
start=/usr/local/bin/hyper-profile gaming
; Al salir: vuelta a desarrollo
end=/usr/local/bin/hyper-profile dev
