# HyperArch — Crimson Glass
font_family      JetBrainsMono Nerd Font
font_size        11.5
bold_font        auto
italic_font      auto

background            #090909
foreground            #d6e4f3
cursor                #2f9bff
selection_background  #6d3cff
selection_foreground  #d6e4f3

background_opacity    0.85
background_blur       32
dynamic_background_opacity yes

window_padding_width  10
hide_window_decorations yes
confirm_os_window_close 0

# negro / rojo / verde / amarillo / azul / magenta / cian / blanco
color0 #141822
color8 #55606e
color1 #ff3b5c
color9 #ff6b85
color2 #4ade80
color10 #86efac
color3 #fbbf24
color11 #fcd34d
color4 #2f9bff
color12 #6dbcff
color5 #6d3cff
color13 #a78bfa
color6 #22d3ee
color14 #67e8f9
color7 #d6e4f3
color15 #ffffff

scrollback_lines 20000
enable_audio_bell no
