# HyperArch — Crimson Glass
font_family      JetBrainsMono Nerd Font
font_size        11.5
bold_font        auto
italic_font      auto

background            #090909
foreground            #f3d6d9
cursor                #ff1e3c
selection_background  #8b0020
selection_foreground  #f3d6d9

background_opacity    0.85
background_blur       32
dynamic_background_opacity yes

window_padding_width  10
hide_window_decorations yes
confirm_os_window_close 0

# negro / rojo / verde / amarillo / azul / magenta / cian / blanco
color0 #1a1416
color8 #6b5658
color1 #ff1e3c
color9 #ff5c78
color2 #4ade80
color10 #86efac
color3 #fbbf24
color11 #fcd34d
color4 #60a5fa
color12 #93c5fd
color5 #c084fc
color13 #d8b4fe
color6 #22d3ee
color14 #67e8f9
color7 #f3d6d9
color15 #ffffff

scrollback_lines 20000
enable_audio_bell no
