# HyperArch — gestión de inactividad
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Atenuar aviso: apagar pantallas a los 10 min
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Bloquear a los 15 min
listener {
    timeout = 900
    on-timeout = loginctl lock-session
}

# Suspender a los 30 min (suspensión a RAM; sin hibernación por diseño, RR-05)
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
