preload = /usr/share/hyperarch/wallpapers/hyperarch-crimson.png
preload = /usr/share/hyperarch/wallpapers/hyperarch-crimson-vertical.png
wallpaper = DP-1, /usr/share/hyperarch/wallpapers/hyperarch-crimson.png
wallpaper = DP-2, /usr/share/hyperarch/wallpapers/hyperarch-crimson-vertical.png
wallpaper = , /usr/share/hyperarch/wallpapers/hyperarch-crimson.png
splash = false
ipc = on
