preload = /usr/share/hyperarch/wallpapers/hyperarch-blue.png
preload = /usr/share/hyperarch/wallpapers/hyperarch-blue-vertical.png
wallpaper = DP-1, /usr/share/hyperarch/wallpapers/hyperarch-blue.png
wallpaper = DP-2, /usr/share/hyperarch/wallpapers/hyperarch-blue-vertical.png
wallpaper = , /usr/share/hyperarch/wallpapers/hyperarch-blue.png
splash = false
ipc = on

# Paleta alternativa (carmesí):
#   wallpaper = DP-1, /usr/share/hyperarch/wallpapers/hyperarch-crimson.png
