# HyperArch — pantalla de bloqueo
general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = /usr/share/hyperarch/wallpapers/hyperarch-blue.png
    blur_passes = 3
    blur_size = 8
    brightness = 0.6
}

input-field {
    monitor =
    size = 320, 52
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgb(2f9bff)
    inner_color = rgb(0d0f14)
    font_color = rgb(d6e4f3)
    check_color = rgb(fbbf24)
    fail_color = rgb(6d3cff)
    rounding = 14
    placeholder_text = <i>contraseña</i>
    fade_on_empty = true
}

label {
    monitor =
    text = $TIME
    position = 0, 80
    halign = center
    valign = center
    color = rgb(d6e4f3)
    font_size = 72
    font_family = JetBrainsMono Nerd Font
}

label {
    monitor =
    text = HyperArch
    position = 0, -180
    halign = center
    valign = center
    color = rgb(2f9bff)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
}
