# HyperArch — pantalla de bloqueo
general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = /usr/share/hyperarch/wallpapers/hyperarch-crimson.png
    blur_passes = 3
    blur_size = 8
    brightness = 0.6
}

input-field {
    monitor =
    size = 320, 52
    position = 0, -80
    halign = center
    valign = center
    outline_thickness = 2
    outer_color = rgb(ff1e3c)
    inner_color = rgb(0f0d0e)
    font_color = rgb(f3d6d9)
    check_color = rgb(fbbf24)
    fail_color = rgb(8b0020)
    rounding = 14
    placeholder_text = <i>contraseña</i>
    fade_on_empty = true
}

label {
    monitor =
    text = $TIME
    position = 0, 80
    halign = center
    valign = center
    color = rgb(f3d6d9)
    font_size = 72
    font_family = JetBrainsMono Nerd Font
}

label {
    monitor =
    text = HyperArch
    position = 0, -180
    halign = center
    valign = center
    color = rgb(ff1e3c)
    font_size = 14
    font_family = JetBrainsMono Nerd Font
}
