# HyperArch — tema "Production"
general {
    gaps_in = 2
    gaps_out = 5
    border_size = 1
    col.active_border = rgba(2f9bffff)
    col.inactive_border = rgba(222834ff)
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 5
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0
    dim_inactive = false
    blur { enabled = false }
    shadow { enabled = false }
}

animations {
    enabled = true
    bezier = instant, 0.1, 1, 0.1, 1
    animation = windowsIn,   1, 1.5, instant
    animation = windowsOut,  1, 1,   instant
    animation = windowsMove, 1, 1.5, instant
    animation = fadeIn,      1, 1,   instant
    animation = fadeOut,     1, 1,   instant
    animation = workspaces,  1, 1.5, instant
    animation = border,      1, 1,   instant
    animation = borderangle, 0
    animation = layers,      0
}

dwindle { preserve_split = true; smart_resizing = true }

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 1
    background_color = 0x090909
}
